// gui-electron/src/renderer/components/Timeline.vue
<template>
  <div :style="timelineStyle()">
    <template v-for="(component, index) in Array.from(components.values())">
      <div
        class="component"
        :key="component.id"
        :style="componentStyle(component, index)"
        @click='$emit("select", component.id)'
      >
        {{ component.id.slice(0,5) }}
      </div>
    </template>
  </div>
</template>

<script>
  export default {
    name: 'timeline',
    props: [ 'components', 'selected' ],
    methods: {
      componentStyle (component, index) {
        return {
          position: 'absolute',
          top: `${index * 30}px`,
          left: `${component.start_time}px`,
          width: `${component.length}px`,
          display: 'block',
          backgroundColor: component.id === this.selected ? '#fcc' : '#f99',
          padding: '5px',
        };
      },
      timelineStyle () {
        return {
          position: 'relative',
          height: '10rem',
          overflowY: 'scroll',
        }
      }
    },
  }
</script>

// gui-electron/src/components/timeline.jsx
import * as React from "react";

export default class Timeline extends React.Component {
	render() {
		const style = {
			position: "relative",
			height: "10rem",
			overflowY: "scroll"
		};

		return (
			<div className="timeline" style={style}>
				{Array.from(this.props.fetchComponents().values()).map(
					(comp, index) => {
						const style = {
							position: "absolute",
							top: index * 20,
							left: comp.start_time,
							width: comp.length,
							display: "block",
							backgroundColor:
								this.props.fetchSelected() === comp.id ? "#fcc" : "#f99"
						};

						return (
							<div
								key={comp.id}
								style={style}
								onClick={() => {
									this.props.onSelectComponent(comp.id);
								}}
							>
								{comp.id.slice(0, 5)}
							</div>
						);
					}
				)}
			</div>
		);
	}
}
