// gui-electron/src/components/screen.jsx
import React, { Component } from "react";
import { Receiver, Request } from "../lib";

export default class Screen extends Component {
	constructor(props) {
		super(props);

		this.screen = React.createRef();
		this.src = "";
	}

	renderScreen(value: number) {
		this.props.comm.send(
			Request.Get(`/screen/${value}`),
			Receiver.receive(response => {
				this.src = JSON.parse(response);

				const context = this.screen.current.getContext("2d");
				const image = new Image();
				image.onload = () => {
					context.drawImage(image, 0, 0, 640, 480);
				};
				image.src = this.src;
			})
		);
	}

	render() {
		return (
			<div>
				<canvas ref={this.screen} width="640px" height="480px" />
			</div>
		);
	}
}

// gui-electron/src/renderer/components/Screen.vue
<template>
  <div>
    <canvas ref="screen" width="640px" height="480px" />
  </div>
</template>

<script>
  import { Communicator, Request, Receiver, cast_as, Component } from "@/lib";

  export default {
    name: 'screen',
    props: [ 'fetchScreen', 'position' ],
    methods: {
      changePosition () {
        this.fetchScreen(this.position, b64str => {
          const src = JSON.parse(b64str);

          const context = this.$refs.screen.getContext('2d');
          const image = new Image();
          image.onload = () => {
            context.drawImage(image, 0, 0, 640, 480);
          };
          image.src = src;
        });
      }
    },
    watch: {
      position (newPosition, oldPosition) {
        this.changePosition();
      }
    },
    mounted () {
      this.changePosition();
    },
  }
</script>
