// gui-electron/src/components/App.jsx
import "./App.css";
import { Component, Receiver, Request, cast_as } from "../lib.js";
import React from "react";
import Button from "@material-ui/core/Button";
import Slider from "@material-ui/lab/Slider";
import Screen from "./screen";
import Timeline from "./timeline";
import ComponentDetail from "./component_detail";
import Ruler from "./ruler";
import AddIcon from "@material-ui/icons/Add";
import NewComponent from "./new_component";

const remote = window.require ? window.require("electron").remote : null;

// App will manage component-related state
// and share the state to all other children components
class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      value: 0,
      components: new Map(),
      selected: null,
      open: false
    };

    this.timeline = React.createRef();
    this.componentDetail = React.createRef();
    this.screen = React.createRef();

    window.onload = event => {
      // After fetching components from server,
      // Components which contains components information need to be updated
      this.updateComponents();
      this.screen.current.renderScreen(0);
    };
  }

  updateComponents() {
    this.props.comm.send(
      Request.Get("/component"),
      Receiver.receive(response => {
        const comps = JSON.parse(response);

        let cmap = new Map();
        comps.forEach(_comp => {
          let comp = cast_as(Component.fromObject(_comp), Component);
          cmap.set(comp.id, comp);
        });

        this.setState({
          components: cmap
        });
      })
    );
  }

  // When updating the component state,
  // some React.Components need to be rerendered
  shouldComponentUpdate() {
    this.timeline.current.forceUpdate();
    this.componentDetail.current.forceUpdate();

    return true;
  }

  createNewComponent = (component, callback) => {
    this.props.comm.send(
      Request.Create("/component", component),
      Receiver.receive(data => {
        this.updateComponents();

        if (callback != null) {
          callback(data);
        }
      })
    );
  };

  updatePosition = (event, value) => {
    this.setState({ value: value });
    this.screen.current.renderScreen(value);
    console.log("position: ", value);
  };

  updateCurrentComponentAttribute = (key, value) => {
    let components = this.state.components;
    let current = this.state.components.get(this.state.selected);
    if (key === "start_time") {
      let start_time = parseInt(value, 10);
      current.start_time = start_time;

      components.set(current.id, current);
      this.setState({
        components: components
      });

      // Error handling...
      this.props.comm.send(
        Request.Update(`/component/${current.id}`, { start_time: start_time }),
        Receiver.discard()
      );
    } else if (key === "length") {
      let length = parseInt(value, 10);
      current.length = length;

      components.set(current.id, current);
      this.setState({
        components: components
      });

      // Error handling...
      this.props.comm.send(
        Request.Update(`/component/${current.id}`, { length: length }),
        Receiver.discard()
      );
    } else {
      throw new Error(`Invalid key: ${key}`);
    }
  };

  render() {
    return (
      <div className="App">
        <Screen comm={this.props.comm} ref={this.screen} />
        <Ruler />
        <Slider
          ref={this.slider}
          min={0}
          max={1000}
          value={this.state.value}
          step={10}
          aria-labelledby="label"
          onChange={this.updatePosition}
        />
        <Timeline
          ref={this.timeline}
          fetchComponents={() => this.state.components}
          fetchSelected={() => this.state.selected}
          onSelectComponent={id => this.setState({ selected: id })}
        />
        <ComponentDetail
          ref={this.componentDetail}
          fetchSelectedComponent={() =>
            this.state.components.get(this.state.selected)
          }
          updateCurrentComponentAttribute={this.updateCurrentComponentAttribute}
        />
        <Button
          variant="contained"
          color="primary"
          aria-label="Delete"
          onClick={() => this.setState({ open: true })}
        >
          <AddIcon />
          New Component
        </Button>
        <NewComponent
          open={this.state.open}
          onClose={() => this.setState({ open: false })}
          onSubmit={this.createNewComponent}
        />
      </div>
    );
  }
}

export default App;

// gui/src/renderer/App.vue
<template>
  <div ref="app" id="app">
    <screen :fetchScreen="fetchScreen" :position="position" />
    <vs-slider @change="changePosition" v-model.number="position" type="number" :min=0 :max=100 />
    {{ this.position }} sec
    <vs-button @click="tickProject">next</vs-button>
    <timeline ref="timeline" :components="components" :selected="selected" v-on:select="selectById" />
    <add-component v-on:submit-new-component="createNewComponent" />
    <component-detail ref="componentDetail" :component="selectedComponent" v-on:change-attr="changeAttrOnSelected" />
    <write-options ref="writeOptions" v-on:submit-start-render="startRender" />
  </div>
</template>

<script>
  import Screen from '@/components/Screen';
  import Timeline from '@/components/Timeline';
  import AddComponent from '@/components/AddComponent';
  import ComponentDetail from '@/components/ComponentDetail';
  import WriteOptions from '@/components/WriteOptions';
  import { Communicator, Request, Receiver, cast_as, Component } from '@/lib';
  import { ipcRenderer } from 'electron';

  export default {
    name: 'gui-madder',
    components: {
      Screen,
      Timeline,
      AddComponent,
      ComponentDetail,
      WriteOptions,
    },
    data () {
      return {
        comm: new Communicator(() => {
          this.updateComponents();
        }, (err) => {
          console.log("=== Error ===");
          console.log(err);
          console.table(err);
        }),
        components: new Map(),
        selected: null,
        position: 0,
      };
    },
    computed: {
      selectedComponent () {
        return this.components.get(this.selected);
      }
    },
    methods: {
      updateComponents () {
        this.comm.send(
          Request.Get('/component'),
          Receiver.receive(response => {
            const comps = JSON.parse(response);

            let cmap = new Map();
            comps.forEach(_comp => {
              let comp = cast_as(Component.fromObject(_comp), Component);
              cmap.set(comp.id, comp);
            });

            this.components = cmap;
          })
        );
      },
      createNewComponent (component, callback) {
        this.comm.send(
          Request.Create('/component', component),
          Receiver.receive(data => {
            this.updateComponents();

            if (callback != null) {
              callback(data);
            }
          })
        );
      },
      selectById (component_id) {
        this.selected = component_id;
      },
      changePosition (value) {
        this.position = value;
      },
      fetchScreen (position, callback) {
        this.comm.send(
          Request.Get(`/screen/${position * 1000}`),
          Receiver.receive(callback),
        );
      },
      changeAttrOnSelected (key, value) {
        const current = this.components.get(this.selected);

        this.comm.send(
          Request.Update(`/component/${current.id}`, { [key]: value }),
          Receiver.discard()
        );

        // This is not enough to trigger update for timeline, but why?
        this.$set(this.components, this.selected, Object.assign({ [key]: value }, this.selectedComponent));

        this.$refs.timeline.$forceUpdate();
        this.$refs.componentDetail.$forceUpdate();
      },
      startRender (config) {
        this.comm.send(
          Request.Create("/write", config),
          Receiver.receiveUntil(data => {
            console.log(`rendering finished! ${data}`);
          }, data => data === "")
        );
      },
      tickProject () {
        this.comm.send(
          Request.Create('/project/tick', {}),
          Receiver.discard(),
        );
      },
    },
    mounted () {
      // file read/write
      ipcRenderer.on("open-yaml", (event, arg) => {
        this.comm.send(
          Request.Update("/project/yaml", arg),
          Receiver.receive(data => {
            this.updateComponents();
          })
        );
      });

      ipcRenderer.on("request-save-yaml", (event, arg) => {
        this.comm.send(
          Request.Get("/project/yaml"),
          Receiver.receive(data => {
            ipcRenderer.send("response-save-yaml", data);
          })
        );
      });

      ipcRenderer.on("request-write-avi-file", (event, arg) => {
        this.$refs.writeOptions.active();
      });
    },
  }
</script>

<style>
  /* CSS */
</style>
